// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgnvYhDZGx-YTy7gTrFlGPm6-acPq3uVE',
    appId: '1:720936035879:web:158c173c0b4c5924791002',
    messagingSenderId: '720936035879',
    projectId: 'panoptesan-c6ef1',
    authDomain: 'panoptesan-c6ef1.firebaseapp.com',
    storageBucket: 'panoptesan-c6ef1.appspot.com',
    measurementId: 'G-52GQY4ET58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf15aDY3BRQ1PBQTRu1h7b3uyjg8YtSpY',
    appId: '1:720936035879:android:834a385d5c38e861791002',
    messagingSenderId: '720936035879',
    projectId: 'panoptesan-c6ef1',
    storageBucket: 'panoptesan-c6ef1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy7LGSxNGQPquySKYsBVJEsuJI8BnF6bI',
    appId: '1:720936035879:ios:8ce0ee1811bf8392791002',
    messagingSenderId: '720936035879',
    projectId: 'panoptesan-c6ef1',
    storageBucket: 'panoptesan-c6ef1.appspot.com',
    androidClientId: '720936035879-2vge33l56mnkr34ra35gk6j2mf21k08q.apps.googleusercontent.com',
    iosClientId: '720936035879-mb7578mjmoal1k90tl1lt1egbvl908tr.apps.googleusercontent.com',
    iosBundleId: 'com.thesuitch.panoptesan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy7LGSxNGQPquySKYsBVJEsuJI8BnF6bI',
    appId: '1:720936035879:ios:fd7d855a6729b95c791002',
    messagingSenderId: '720936035879',
    projectId: 'panoptesan-c6ef1',
    storageBucket: 'panoptesan-c6ef1.appspot.com',
    androidClientId: '720936035879-2vge33l56mnkr34ra35gk6j2mf21k08q.apps.googleusercontent.com',
    iosClientId: '720936035879-9ce5aiqeehpjtv94devm0o96c67o1u8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.panoptesanAlpha',
  );
}
